# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-08-07 05:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20200803_2314'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricePolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catogory', models.SmallIntegerField(choices=[(1, '免费版'), (2, 'VIP版'), (3, 'SVIP版')], default=1, verbose_name='收费类型')),
                ('price', models.PositiveIntegerField(verbose_name='价格')),
                ('poject_num', models.PositiveIntegerField(verbose_name='项目数量')),
                ('poject_member', models.PositiveIntegerField(verbose_name='项目成员人数')),
                ('project_space', models.PositiveIntegerField(verbose_name='每个项目空间')),
                ('per_file_size', models.PositiveIntegerField(verbose_name='单文件大小')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='项目名称')),
                ('color', models.IntegerField(choices=[(1, '#4EEE94'), (2, '#FFD700'), (3, '#90EE90'), (4, '#BF3EFF'), (5, '#FF34B3'), (6, '#FF6347'), (7, '#9370DB')], verbose_name='颜色')),
                ('desc', models.CharField(blank=True, max_length=64, null=True, verbose_name='项目描述')),
                ('use_space', models.IntegerField(default=0, verbose_name='项目已用空间')),
                ('star', models.BooleanField(default=False, verbose_name='星标')),
                ('join_count', models.IntegerField(default=1, verbose_name='参与人数')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.BooleanField(default=False, verbose_name='星标')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Project', verbose_name='项目')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(1, '未支付'), (2, '已支付')], default=1, verbose_name='状态')),
                ('order', models.CharField(max_length=64, unique=True, verbose_name='订单号')),
                ('count', models.IntegerField(help_text='0表示无限期', verbose_name='数量(年)')),
                ('price', models.IntegerField(verbose_name='实际支付价格')),
                ('start_datetime', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_datetime', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('create_datetime', models.DateTimeField(null=True, verbose_name='创建时间')),
                ('price_policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.PricePolicy', verbose_name='价格策略')),
            ],
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='email',
            field=models.EmailField(max_length=32, unique=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='username',
            field=models.CharField(max_length=32, unique=True, verbose_name='用户名'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.UserInfo', verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='projectuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.UserInfo', verbose_name='参与者'),
        ),
        migrations.AddField(
            model_name='project',
            name='create',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.UserInfo', verbose_name='创建者'),
        ),
    ]
