# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-08-07 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_auto_20200807_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=32, verbose_name='项目名称'),
        ),
    ]
