# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-08-09 02:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_auto_20200807_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricepolicy',
            name='catogory',
            field=models.SmallIntegerField(choices=[(1, '免费版'), (2, 'VIP'), (3, 'SVIP')], default=1, verbose_name='收费类型'),
        ),
        migrations.AlterField(
            model_name='pricepolicy',
            name='per_file_size',
            field=models.PositiveIntegerField(help_text='单位是M', verbose_name='单文件大小'),
        ),
        migrations.AlterField(
            model_name='pricepolicy',
            name='project_space',
            field=models.PositiveIntegerField(help_text='单位是M', verbose_name='每个项目空间'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='create_datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
    ]
