# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-08-09 03:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_auto_20200809_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricepolicy',
            name='title',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='标题'),
        ),
    ]
