# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-08-09 04:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0010_pricepolicy_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricepolicy',
            old_name='poject_member',
            new_name='project_member',
        ),
        migrations.RenameField(
            model_name='pricepolicy',
            old_name='poject_num',
            new_name='project_num',
        ),
    ]
