# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-08-09 09:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0011_auto_20200809_1207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='create',
            new_name='creator',
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together=set([('name', 'creator')]),
        ),
    ]
