# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-08-11 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0013_auto_20200809_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='color',
            field=models.IntegerField(choices=[(1, '#4EEE94'), (2, '#FFD700'), (3, '#90EE90'), (4, '#BF3EFF'), (5, '#FF34B3'), (6, '#FF6347'), (7, '#9370DB')], default=1, verbose_name='颜色'),
        ),
    ]
