# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-08-15 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0015_wiki'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='bucket',
            field=models.CharField(default=1, max_length=60, verbose_name='oss桶'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='region',
            field=models.CharField(default=1, max_length=32, verbose_name='oss区域'),
            preserve_default=False,
        ),
    ]
