# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-08-17 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0017_filerepository'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filerepository',
            name='file_type',
            field=models.BigIntegerField(choices=[(1, '文件'), (2, '文件夹')], verbose_name='类型'),
        ),
    ]
