# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-08-17 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0018_auto_20200817_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filerepository',
            name='file_size',
            field=models.IntegerField(blank=True, help_text='单位为B', null=True, verbose_name='文件大小'),
        ),
        migrations.AlterField(
            model_name='filerepository',
            name='file_type',
            field=models.SmallIntegerField(choices=[(1, '文件'), (2, '文件夹')], verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='project',
            name='use_space',
            field=models.BigIntegerField(default=0, verbose_name='项目已用空间'),
        ),
    ]
